### PR TITLE
Version running on Cardiff University servers

### PR DESCRIPTION
**Pull request by jamesdav2343**
Docker version of FreeTxt running on Cardiff University servers at the moment.

### CODE REVIEW

**Comment by JohnVidler** [comment]
Resolved the conflicts with the upstream branch, and merging down to rebuild the docker image

**Comment by JohnVidler** [comment]
@james-hulud I've gone ahead with the merge, but can you please summarise the changes included in a comment here please? Just for documentation's sake when we come back to this and wonder what was going on :)

**Comment by jamesdav2343** [comment]
@JohnVidler 

Sure here you go :)

List of changes in this version, compared to original feature/docker branch:

**Small changes:**

Meaning analysis - Column title changed from "Sentiment score" to "Confidence score"

Sentiment chart - "Characteristic" header made fully visible

logs - separate logs for general info and errors only

**Larger changes:**

Aspect-based sentiment analysis initial implementation (Not working in Welsh)

Word Cloud - overhauled. Word list in menu either as side bar or beneath cloud. Search bar above word list. Instead of regenerating after selected one word / tag, now can select multiple words / tags then update cloud. Semantic tag changes: Word and tag associations beneath cloud. Radio to show words that are assigned the selected semantic tags. Changed filtering of dataset, now every selected word / tag / etc will always appear in the word cloud instead of either not appearing or generating an error.

Word Tree - menu added containing punctuation. Option to remove specific punctuation from word tree dataset.

Word Use and Relationships - select dropdown changed. Search bar added. Checkbox to include any filtered out data in dropdown. Options to download filtered and unfiltered datasets.

File size limit set on flask backend, currently 1MB for uploaded files.

Bug fixes. word use: fixed issue where certain selected semantic tags would not work. General: when errors are caught, app is still useable, loading screen is hidden. Does not load infinitely. Lots of other general fixes. Dark mode now saves to session correctly.

requirements.txt updated

Welsh translations added for new changes.

**Comment by JohnVidler** [comment]
Spot on, thank you for that!

**Pull request merged**
